<?xml version="1.0"?>
<robot name="cartBot_2wd" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="base_length" value="0.338" />
  <xacro:property name="base_width" value="0.32" />
  <xacro:property name="base_height" value="0.005" />
  <xacro:property name="base_mass" value="5" />
  <!-- set empty on the wheel_mesh_file to use geometry instead of mesh -->
  <xacro:property name="base_mesh_file" value="" />
  <!-- <xacro:property name="base_mesh_file" value="file://$(find cartBot_description)/meshes/base.dae" /> -->


  <xacro:property name="wheel_radius" value="0.0675" />
  <xacro:property name="wheel_width" value="0.022" />
  <xacro:property name="wheel_pos_x" value="0.1015" />
  <xacro:property name="wheel_pos_y" value="0.18" />
  <xacro:property name="wheel_pos_z" value="-0.0125" />
  <xacro:property name="wheel_mass" value=".1" />
  <xacro:property name="wheel_torque" value="40" />
  <xacro:property name="front_caster_wheel" value="false" />
  <xacro:property name="rear_caster_wheel" value="true" />

  <!-- set empty on the wheel_mesh_file to use geometry instead of mesh -->
  <xacro:property name="wheel_mesh_file" value="" />
  <!-- <xacro:property name="wheel_mesh_file" value="file://$(find cartBot_description)/meshes/tire.dae" /> -->

  <xacro:include filename="$(find cartBot_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/mech/caster_wheel.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/sensors/depth_sensor.urdf.xacro" />
  <xacro:include filename="$(find cartBot_description)/urdf/controllers/diff_drive.urdf.xacro" />

  <xacro:property name="laser_pose">
    <origin xyz="0.126 0 0.25" rpy="0 0 -0.78539816339"/>
  </xacro:property>

  <xacro:property name="base_laser_pose">
    <origin xyz="0.179 0 -0.045" rpy="-3.1416 0 0"/>
  </xacro:property>

  <xacro:property name="depth_sensor_pose">
    <origin xyz="0.194 0.0 0.185" rpy="0 0 0"/>
  </xacro:property>

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
    mesh_file="${base_mesh_file}"
  />

  <xacro:wheel 
    side="left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    mesh_file="${wheel_mesh_file}"
  />

  <xacro:wheel 
    side="right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    mesh_file="${wheel_mesh_file}"
  />

  <xacro:if value="${front_caster_wheel}">
    <xacro:caster_wheel 
      side="front"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:if value="${rear_caster_wheel}">
    <xacro:caster_wheel 
      side="rear"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:imu/>

  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  
  <xacro:generic_base_laser>
    <xacro:insert_block name="base_laser_pose" />
  </xacro:generic_base_laser>
  
  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>