name: colcon build

on:
  pull_request:
    branches: [ jazzy ]  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-24.04 
    steps:
    - uses: actions/checkout@v4
    - name: Install and Build ROS2 environment
      run: |
        export UBUNTU_VER=24.04
        export USE_ROS_DISTRO=jazzy
        export RMW=cyclonedds
        cd docker && docker compose build
      shell: bash
    - name: Nvidia - Install and Build ROS2 environment
      run: |
        export UBUNTU_VER=24.04
        export USE_ROS_DISTRO=jazzy
        export RMW=cyclonedds
        export RUNTIME=nvidia
        cd docker && docker compose build
      shell: bash