scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_laser
        max_x: 12.
        max_y: 12.
        max_z: 0.5
        min_x: 0.0
        min_y: -12.
        min_z: -0.5
        
        invert: true # activate to remove all points outside of the box