name: Pull Request CI

on:
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - '**'

jobs:

    CI:
        uses: ./.github/workflows/ci.yml
        with:
            ci_target_ref: ${{ github.event.pull_request.head.ref }}
