name: ROS Galactic Firmware Build

on:
  pull_request:
    # Run on PRs only to branches starting with 'galactic'
    branches:
      - galactic*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  push:
    # Run on pushes only to branches starting with 'galactic'
    branches:
      - galactic*
    # Don't run when the following files are changed which don't effect firmware.
    paths-ignore:
      - 'docs/**'
      - .gitignore
      - LICENSE
      - README.md
  
  # Run daily at midnight to detect flakiness and broken dependencies
  schedule:
    - cron: '0 0 * * *'

  # Allow manual triggering
  workflow_dispatch:


jobs:
  firmware:
    # The current file calls the firmware workflow with the following parameters
    uses: ./.github/workflows/reusable-platformio-ci.yml
    with:
      ros_distro: galactic
      # The reference field will be set to 'galactic' only if the event that triggered the workflow is schedule. Otherwise, it will be left blank.
      reference: ${{ github.event_name == 'schedule' && 'galactic' || '' }}
